# Hate Speech Classification Assignment (RNN)

## Load Data

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('imbalanced_data.csv')
data.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [3]:
df = data.drop(columns=['id'])
df.head()

   label                                              tweet
0      0   @user when a father is dysfunctional and is s...
1      0  @user @user thanks for #lyft credit i can't us...
2      0                                bihday your majesty
3      0  #model   i love u take with u all the time in ...
4      0             factsguide: society now    #motivation

## Text Cleaning

In [4]:
df['tweet'] = df['tweet'].str.lower()
df['tweet'].head()

0     @user when a father is dysfunctional and is s...
1    @user @user thanks for #lyft credit i can't us...
2                                  bihday your majesty
3    #model   i love u take with u all the time in ...
4               factsguide: society now    #motivation
Name: tweet, dtype: object

In [5]:
df['tweet'] = df['tweet'].str.replace(r'(@\S+)|(https?://\S+)|([^a-zA-Z\s])', ' ', regex=True)
df['tweet'].head()

0       when a father is dysfunctional and is so se...
1        thanks for  lyft credit i can t use cause ...
2                                  bihday your majesty
3     model   i love u take with u all the time in ...
4               factsguide  society now     motivation
Name: tweet, dtype: object

In [6]:
df['tweet'] = df['tweet'].str.strip()
df['tweet'].head()

0    when a father is dysfunctional and is so selfi...
1    thanks for  lyft credit i can t use cause they...
2                                  bihday your majesty
3      model   i love u take with u all the time in ur
4               factsguide  society now     motivation
Name: tweet, dtype: object

## Tokenization & Vocabulary

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
vocab_size = 5000
tokenizer = Tokenizer(
    num_words=vocab_size,
    oov_token = "<OOV"
)

In [10]:
tokenizer.fit_on_texts(df['tweet'])

## Text to Sequences

In [12]:
sequences = tokenizer.texts_to_sequences(df['tweet'])

In [26]:
lengths = [len(seq) for seq in sequences]
import numpy as np
print(np.percentile(lengths, [50, 75, 90, 95, 99]))

[12. 16. 20. 22. 26.]

In [27]:
padded = pad_sequences(sequences,maxlen=22,padding='post',truncating='post')

In [28]:
word_index = tokenizer.word_index

print("Word Index:", word_index)
print("Sequences:", sequences)
print("Padded:", padded)

Word Index: {'<OOV': 1, 'the': 2, 'to': 3, 'i': 4, 'a': 5, 'you': 6, 'and': 7, 'in': 8, 'for': 9, 'of': 10, 'is': 11, 'my': 12, 'it': 13, 's': 14, 'love': 15, 'this': 16, 'on': 17, 'with': 18, 'be': 19, 't': 20, 'day': 21, 'that': 22, 'all': 23, 'so': 24, 'are': 25, 'me': 26, 'amp': 27, 'happy': 28, 'your': 29, 'at': 30, 'have': 31, 'we': 32, 'am': 33, 'can': 34, 'just': 35, 'will': 36, 'when': 37, 'not': 38, 'do': 39, 'u': 40, 'like': 41, 'life': 42, 'what': 43, 'time': 44, 'm': 45, 'but': 46, 'today': 47, 'from': 48, 'up': 49, 'now': 50, 'new': 51, 'thankful': 52, 'out': 53, 'as': 54, 'positive': 55, 'get': 56, 'was': 57, 'people': 58, 'bihday': 59, 'good': 60, 'about': 61, 'how': 62, 'our': 63, 'by': 64, 'no': 65, 'they': 66, 'one': 67, 'see': 68, 'smile': 69, 'more': 70, 'if': 71, 'don': 72, 'go': 73, 'who': 74, 'father': 75, 'want': 76, 'he': 77, 'take': 78, 'work': 79, 'fun': 80, 'healthy': 81, 'weekend': 82, 're': 83, 'summer': 84, 'an': 85, 'has': 86, 'there': 87, 'or': 88, 'make': 89, 'family': 90, 'got': 91, 'us': 92, 'friday': 93, 'days': 94, 'beautiful': 95, 'best': 96, 'friends': 97, 'here': 98, 'great': 99, 'his': 100, 'need': 101, 'way': 102, 'why': 103, 'bull': 104, 'only': 105, 'going': 106, 'first': 107, 'really': 108, 'their': 109, 'music': 110, 'morning': 111, 'wait': 112, 'world': 113, 'back': 114, 'ur': 115, 'tomorrow': 116, 'week': 117, 'know': 118, 'some': 119, 'cute': 120, 'been': 121, 'very': 122, 'sad': 123, 'orlando': 124, 'fathersday': 125, 'never': 126, 'her': 127, 'think': 128, 'trump': 129, 'too': 130, 'being': 131, 'happiness': 132, 'right': 133, 'blog': 134, 'girl': 135, 'sunday': 136, 'off': 137, 'feel': 138, 'after': 139, 'home': 140, 'night': 141, 'model': 142, 'much': 143, 'follow': 144, 'affirmation': 145, 'had': 146, 've': 147, 'always': 148, 'live': 149, 'next': 150, 'she': 151, 'well': 152, 'even': 153, 'them': 154, 'year': 155, 'finally': 156, 'last': 157, 'because': 158, 'come': 159, 'd': 160, 'amazing': 161, 'over': 162, 'still': 163, 'than': 164, 'these': 165, 'dad': 166, 'gold': 167, 'selfie': 168, 'thanks': 169, 'ready': 170, 'thank': 171, 'tonight': 172, 'look': 173, 'silver': 174, 'things': 175, 'fathers': 176, 'find': 177, 'gt': 178, 'makes': 179, 'altwaystoheal': 180, 'via': 181, 'let': 182, 'little': 183, 'then': 184, 'many': 185, 'again': 186, 'free': 187, 'man': 188, 'pay': 189, 'everyone': 190, 'him': 191, 'old': 192, 'show': 193, 'looking': 194, 'would': 195, 'ever': 196, 'll': 197, 'forex': 198, 'feeling': 199, 'blessed': 200, 'another': 201, 'down': 202, 'black': 203, 'hope': 204, 'peace': 205, 'game': 206, 'god': 207, 'getting': 208, 'girls': 209, 'its': 210, 'enjoy': 211, 'most': 212, 'news': 213, 'food': 214, 'should': 215, 'watch': 216, 'city': 217, 'bear': 218, 'stop': 219, 'sta': 220, 'climb': 221, 'sun': 222, 'hate': 223, 'say': 224, 'th': 225, 'friend': 226, 'saturday': 227, 'made': 228, 'every': 229, 'whatever': 230, 'someone': 231, 'instagood': 232, 'help': 233, 'dog': 234, 'baby': 235, 'white': 236, 'might': 237, 'excited': 238, 'funny': 239, 'may': 240, 'polar': 241, 'keep': 242, 'lol': 243, 'before': 244, 'years': 245, 'n': 246, 'where': 247, 'did': 248, 'any': 249, 'coming': 250, 'nothing': 251, 'beach': 252, 'kids': 253, 'angry': 254, 'having': 255, 'nice': 256, 'into': 257, 'school': 258, 'w': 259, 'cool': 260, 'big': 261, 'awesome': 262, 'healing': 263, 'video': 264, 'hea': 265, 'guys': 266, 'better': 267, 'believe': 268, 'until': 269, 'around': 270, 'long': 271, 'yes': 272, 'please': 273, 'wedding': 274, 'found': 275, 'were': 276, 'grateful': 277, 'done': 278, 'lt': 279, 'holiday': 280, 'won': 281, 'women': 282, 'america': 283, 'quote': 284, 'b': 285, 'proud': 286, 'soon': 287, 'change': 288, 'true': 289, 'direct': 290, 'team': 291, 'monday': 292, 'two': 293, 'waiting': 294, 'thing': 295, 'june': 296, 'motivation': 297, 'lost': 298, 'dominate': 299, 'watching': 300, 'other': 301, 'r': 302, 'such': 303, 'travel': 304, 'bad': 305, 'play': 306, 'something': 307, 'away': 308, 'miss': 309, 'real': 310, 'without': 311, 'euro': 312, 'weeks': 313, 'attack': 314, 'forward': 315, 'end': 316, 'left': 317, 'own': 318, 'hot': 319, 'fashion': 320, 'hair': 321, 'those': 322, 'place': 323, 'photooftheday': 324, 'strong': 325, 'wish': 326, 'playing': 327, 'followme': 328, 'oh': 329, 'face': 330, 'e': 331, 'doing': 332, 'give': 333, 'yeah': 334, 'y': 335, 'racing': 336, 'person': 337, 'check': 338, 'f': 339, 'boy': 340, 'bing': 341, 'libtard': 342, 'didn': 343, 'lovely': 344, 'could': 345, 'bong': 346, 'hard': 347, 'sex': 348, 'rip': 349, 'twitter': 350, 'wow': 351, 'mindset': 352, 'joy': 353, 'x': 354, 'everything': 355, 'racist': 356, 'living': 357, 'buffalo': 358, 'season': 359, 'top': 360, 'does': 361, 'young': 362, 'making': 363, 'yet': 364, 'book': 365, 'gonna': 366, 'health': 367, 'sexy': 368, 'house': 369, 'lot': 370, 'same': 371, 'im': 372, 'doesn': 373, 'l': 374, 'stay': 375, 'tbt': 376, 'leave': 377, 'money': 378, 'job': 379, 'dads': 380, 'london': 381, 'pa': 382, 'tweets': 383, 'moment': 384, 'sleep': 385, 'gay': 386, 'success': 387, 'photo': 388, 'st': 389, 'obama': 390, 'children': 391, 'looks': 392, 'beauty': 393, 'shooting': 394, 'win': 395, 'read': 396, 'said': 397, 'politics': 398, 'pretty': 399, 'words': 400, 'full': 401, 'mom': 402, 'against': 403, 'few': 404, 'yourself': 405, 'poetry': 406, 'men': 407, 'body': 408, 'gorilla': 409, 'already': 410, 'try': 411, 'woman': 412, 'thought': 413, 'says': 414, 'hours': 415, 'mind': 416, 'listen': 417, 'depression': 418, 'quotes': 419, 'thursday': 420, 'inspiration': 421, 'omg': 422, 'couple': 423, 'loved': 424, 'tear': 425, 'working': 426, 'dance': 427, 'perfect': 428, 'head': 429, 'guy': 430, 'truth': 431, 'song': 432, 'environment': 433, 'fitness': 434, 'month': 435, 'o': 436, 'porn': 437, 'p': 438, 'cat': 439, 'since': 440, 'shit': 441, 'while': 442, 'country': 443, 'fuck': 444, 'use': 445, 'super': 446, 'post': 447, 'retweet': 448, 'each': 449, 'call': 450, 'enough': 451, 'must': 452, 'cold': 453, 'isn': 454, 'mood': 455, 'times': 456, 'pm': 457, 'simulator': 458, 'adapt': 459, 'dream': 460, 'run': 461, 'conference': 462, 'also': 463, 'open': 464, 'shop': 465, 'through': 466, 'wonderful': 467, 'which': 468, 'buy': 469, 'simulation': 470, 'media': 471, 'k': 472, 'dead': 473, 'hear': 474, 'rest': 475, 'hour': 476, 'alone': 477, 'business': 478, 'nude': 479, 'both': 480, 'hey': 481, 'meet': 482, 'yay': 483, 'others': 484, 'share': 485, 'crazy': 486, 'race': 487, 'coffee': 488, 'flowers': 489, 'ppl': 490, 'movie': 491, 'wednesday': 492, 'tweet': 493, 'culture': 494, 'gone': 495, 'relax': 496, 'seeing': 497, 'together': 498, 'trying': 499, 'tell': 500, 'put': 501, 'months': 502, 'till': 503, 'comes': 504, 'trip': 505, 'anything': 506, 'smiles': 507, 'sunshine': 508, 'liberal': 509, 'story': 510, 'gift': 511, 'sweet': 512, 'usa': 513, 'lifestyle': 514, 'myself': 515, 'almost': 516, 'care': 517, 'came': 518, 'fans': 519, 'kind': 520, 'daddy': 521, 'forever': 522, 'h': 523, 'son': 524, 'remember': 525, 'tired': 526, 'bed': 527, 'wrong': 528, 'celebrate': 529, 'far': 530, 'thoughts': 531, 'else': 532, 'needs': 533, 'nature': 534, 'goes': 535, 'gym': 536, 'single': 537, 'loving': 538, 'high': 539, 'yesterday': 540, 'tickets': 541, 'allahsoil': 542, 'lives': 543, 'blue': 544, 'prayfororlando': 545, 'empty': 546, 'join': 547, 'delete': 548, 'sorry': 549, 'fact': 550, 'child': 551, '\xa0': 552, 'sick': 553, 'tgif': 554, 'gbp': 555, 'places': 556, 'c': 557, 'actually': 558, 'lgbt': 559, 'social': 560, 'sure': 561, 'anyone': 562, 'aww': 563, 'saw': 564, 'vacation': 565, 'useful': 566, 'power': 567, 'talk': 568, 'side': 569, 'laugh': 570, 'tuesday': 571, 'car': 572, 'photography': 573, 'went': 574, 'goodmorning': 575, 'hardcore': 576, 'instagram': 577, 'word': 578, 'running': 579, '\x85': 580, 'anymore': 581, 'hu': 582, 'hello': 583, 'followers': 584, 'lunch': 585, 'suppo': 586, 'uk': 587, 'nervous': 588, 'deletetweets': 589, 'development': 590, 'reading': 591, 'visit': 592, 'special': 593, 'daily': 594, 'less': 595, 'order': 596, 'evening': 597, 'gun': 598, 'daughter': 599, 'impoant': 600, 'happened': 601, 'victims': 602, 'matter': 603, 'early': 604, 'under': 605, 'gets': 606, 'complete': 607, 'sunny': 608, 'na': 609, 'shopping': 610, 'style': 611, 'football': 612, 'latest': 613, 'anxiety': 614, 'smiling': 615, 'late': 616, 'sometimes': 617, 'history': 618, 'birds': 619, 'app': 620, 'pic': 621, 'green': 622, 'future': 623, 'picoftheday': 624, 'once': 625, 'ago': 626, 'favorite': 627, 'tags': 628, 'usd': 629, 'racism': 630, 'depressed': 631, 'safe': 632, 'boys': 633, 'red': 634, 'families': 635, 'ok': 636, 'lucky': 637, 'guess': 638, 'walk': 639, 'pray': 640, 'sjw': 641, 'park': 642, 'miami': 643, 'cry': 644, 'learn': 645, 'seen': 646, 'cause': 647, 'arrived': 648, 'prayers': 649, 'able': 650, 'everyday': 651, 'wishing': 652, 'vs': 653, 'booked': 654, 'set': 655, 'mean': 656, 'leads': 657, 'florida': 658, 'point': 659, 'vine': 660, 'disney': 661, 'reason': 662, 'dont': 663, 'fucking': 664, 'nd': 665, 'death': 666, 'damn': 667, 'later': 668, 'stas': 669, 'tv': 670, 'education': 671, 'rain': 672, 'sea': 673, 'act': 674, 'brexit': 675, 'date': 676, 'event': 677, 'ass': 678, 'whole': 679, 'close': 680, 'killed': 681, 'become': 682, 'saying': 683, 'target': 684, 'thankyou': 685, 'self': 686, 'understand': 687, 'cant': 688, 'ht': 689, 'july': 690, 'guns': 691, 'youtube': 692, 'homes': 693, 'picture': 694, 'though': 695, 'fan': 696, 'xxx': 697, 'dear': 698, 'finished': 699, 'save': 700, 'conce': 701, 'staing': 702, 'yo': 703, 'talking': 704, 'organizations': 705, 'control': 706, 'snapchat': 707, 'memories': 708, 'update': 709, 'broken': 710, 'seems': 711, 'bless': 712, 'nyc': 713, 'comments': 714, 'anniversary': 715, 'flag': 716, 'state': 717, 'club': 718, 'despite': 719, 'garden': 720, 'goals': 721, 'afternoon': 722, 'reached': 723, 'mad': 724, 'boyfriend': 725, 'break': 726, 'welcome': 727, 'president': 728, 'cannot': 729, 'choose': 730, 'half': 731, 'heard': 732, 'kill': 733, 'used': 734, 'lover': 735, 'episode': 736, 'mother': 737, 'bit': 738, 'friendship': 739, 'smh': 740, 'dreams': 741, 'forget': 742, 'cantwait': 743, 'parents': 744, 'vote': 745, 'happen': 746, 'freedom': 747, 'bring': 748, 'maybe': 749, 'pathetic': 750, 'meeting': 751, 'taking': 752, 'dinner': 753, 'police': 754, 'design': 755, 'fresh': 756, 'animals': 757, 'easy': 758, 'dogs': 759, 'soul': 760, 'wanted': 761, 'hill': 762, 'cake': 763, 'makeup': 764, 'ramadan': 765, 'eyes': 766, 'name': 767, 'kid': 768, 'training': 769, 'breakfast': 770, 'thinking': 771, 'yoga': 772, 'survive': 773, 'hit': 774, 'wife': 775, 'hillary': 776, 'eat': 777, 'affirmations': 778, 'brother': 779, 'rock': 780, 'missing': 781, 'group': 782, 'view': 783, 'reach': 784, 'vicinity': 785, 'dj': 786, 'mountains': 787, 'wants': 788, 'feels': 789, 'called': 790, 'orlandoshooting': 791, 'stuff': 792, 'film': 793, 'oitnb': 794, 'send': 795, 'htt': 796, 'color': 797, 'least': 798, 'final': 799, 'wanna': 800, 'happening': 801, 'heal': 802, 'truly': 803, 'worst': 804, 'moments': 805, 'nasty': 806, 'light': 807, 'leadership': 808, 'chill': 809, 'sister': 810, 'americans': 811, 'tragedy': 812, 'water': 813, 'england': 814, 'india': 815, 'pain': 816, 'crying': 817, 'service': 818, 'voice': 819, 'feelings': 820, 'course': 821, 'g': 822, 'minutes': 823, 'mine': 824, 'v': 825, 'list': 826, 'lighttherapy': 827, 'officially': 828, 'phone': 829, 'different': 830, 'community': 831, 'lawofattraction': 832, 'bought': 833, 'enjoying': 834, 'ask': 835, 'web': 836, 'haven': 837, 'simple': 838, 'festival': 839, 'wtf': 840, 'wishes': 841, 'means': 842, 'ride': 843, 'human': 844, 'past': 845, 'slut': 846, 'american': 847, 'violence': 848, 'instalike': 849, 'during': 850, 'fridayfeeling': 851, 'ahead': 852, 'respect': 853, 'glad': 854, 'along': 855, 'couldn': 856, 'disappointed': 857, 'wake': 858, 'lonely': 859, 'japan': 860, 'sho': 861, 'nbafinals': 862, 'wet': 863, 'reality': 864, 'task': 865, 'gop': 866, 'suppoers': 867, 'queen': 868, 'wine': 869, 'line': 870, 'shot': 871, 'udtapunjab': 872, 'la': 873, 'tears': 874, 'aren': 875, 'present': 876, 'shows': 877, 'beer': 878, 'finding': 879, 'naughty': 880, 'shy': 881, 'sunset': 882, 'staed': 883, 'fantastic': 884, 'tragic': 885, 'using': 886, 'office': 887, 'small': 888, 'mass': 889, 'giving': 890, 'workout': 891, 'agree': 892, 'exciting': 893, 'takes': 894, 'lose': 895, 'instead': 896, 'horny': 897, 'move': 898, 'france': 899, 'room': 900, 'chase': 901, 'needed': 902, 'gotta': 903, 'bday': 904, 'fear': 905, 'lots': 906, 'blonde': 907, 'stupid': 908, 'leaving': 909, 'hatred': 910, 'problem': 911, 'husband': 912, 'rather': 913, 'moving': 914, 'spos': 915, 'congrats': 916, 'die': 917, 'source': 918, 'photos': 919, 'star': 920, 'pink': 921, 'blur': 922, 'drink': 923, 'weather': 924, 'videos': 925, 'muslim': 926, 'actor': 927, 'ways': 928, 'kinky': 929, 'poor': 930, 'stomping': 931, 'behind': 932, 'hell': 933, 'happier': 934, 'dark': 935, 'rooster': 936, 'vast': 937, 'islam': 938, 'local': 939, 'facebook': 940, 'three': 941, 'gave': 942, 'apple': 943, 'teen': 944, 'customer': 945, 'tech': 946, 'pussy': 947, 'instamood': 948, 'busy': 949, 'hi': 950, 'expanse': 951, 'political': 952, 'haha': 953, 'national': 954, 'cats': 955, 'students': 956, 'writing': 957, 'flight': 958, 'class': 959, 'pizza': 960, 'gorgeous': 961, 'sky': 962, 'walking': 963, 'lady': 964, 'experience': 965, 'wonder': 966, 'fit': 967, 'due': 968, 'countdown': 969, 'united': 970, 'puppy': 971, 'loves': 972, 'series': 973, 'yummy': 974, 'babies': 975, 'energy': 976, 'ones': 977, 'luck': 978, 'official': 979, 'college': 980, 'hungry': 981, 'content': 982, 'account': 983, 'seriously': 984, 'york': 985, 'heabroken': 986, 'university': 987, 'ripchristina': 988, 'pride': 989, 'ain': 990, 'woh': 991, 'fall': 992, 'games': 993, 'online': 994, 'adventure': 995, 'street': 996, 'speak': 997, 'loss': 998, 'inshot': 999, 'page': 1000, 'died': 1001, 'mr': 1002, 'pool': 1003, 'internet': 1004, 'hands': 1005, 'scared': 1006, 'vegan': 1007, 'available': 1008, 'co': 1009, 'drinks': 1010, 'instadaily': 1011, 'shame': 1012, 'given': 1013, 'met': 1014, 'vibes': 1015, 'staff': 1016, 'punjab': 1017, 'jobs': 1018, 'took': 1019, 'dancing': 1020, 'told': 1021, 'huge': 1022, 'grow': 1023, 'missed': 1024, 'donald': 1025, 'sale': 1026, 'germany': 1027, 'congratulations': 1028, 'turn': 1029, 'campaign': 1030, 'fly': 1031, 'stand': 1032, 'church': 1033, 'bitch': 1034, 'joke': 1035, 'road': 1036, 'literally': 1037, 'sign': 1038, 'naked': 1039, 'spend': 1040, 'emotions': 1041, 'launch': 1042, 'shoes': 1043, 'absolutely': 1044, 'listening': 1045, 'everybody': 1046, 'inside': 1047, 'xx': 1048, 'camp': 1049, 'king': 1050, 'opening': 1051, 'flower': 1052, 'war': 1053, 'yr': 1054, 'hero': 1055, 'previous': 1056, 'ff': 1057, 'nba': 1058, 'test': 1059, 'vegas': 1060, 'likes': 1061, 'trust': 1062, 'probably': 1063, 'folks': 1064, 'newyork': 1065, 'pre': 1066, 'paris': 1067, 'treat': 1068, 'sense': 1069, 'tips': 1070, 'ex': 1071, 'celebration': 1072, 'okay': 1073, 'dress': 1074, 'confused': 1075, 'trending': 1076, 'female': 1077, 'rd': 1078, 'album': 1079, 'inspirational': 1080, 'idea': 1081, 'snapshot': 1082, 'faith': 1083, 'oil': 1084, 'ice': 1085, 'stories': 1086, 'wasn': 1087, 'christmas': 1088, 'anti': 1089, 'ordered': 1090, 'melancholy': 1091, 'da': 1092, 'secret': 1093, 'bc': 1094, 'aist': 1095, 'realize': 1096, 'step': 1097, 'either': 1098, 'chance': 1099, 'fight': 1100, 'bike': 1101, 'eah': 1102, 'dory': 1103, 'minute': 1104, 'calm': 1105, 'nofilter': 1106, 'alive': 1107, 'married': 1108, 'marriage': 1109, 'choice': 1110, 'low': 1111, 'august': 1112, 'calling': 1113, 'number': 1114, 'nobody': 1115, 'ending': 1116, 'town': 1117, 'successful': 1118, 'born': 1119, 'holidays': 1120, 'pulse': 1121, 'leakage': 1122, 'decided': 1123, 'gif': 1124, 'hrs': 1125, 'asian': 1126, 'message': 1127, 'hand': 1128, 'bag': 1129, 'favourite': 1130, 'spain': 1131, 'ibiza': 1132, 'deep': 1133, 'goodvibes': 1134, 'website': 1135, 'especially': 1136, 'cavs': 1137, 'fire': 1138, 'goodnight': 1139, 'themselves': 1140, 'age': 1141, 'pop': 1142, 'issue': 1143, 'second': 1144, 'stage': 1145, 'bride': 1146, 'towards': 1147, 'release': 1148, 'tried': 1149, 'customers': 1150, 'blogger': 1151, 'knew': 1152, 'changes': 1153, 'fake': 1154, 'tea': 1155, 'fail': 1156, 'celebrating': 1157, 'below': 1158, 'emotional': 1159, 'store': 1160, 'positivity': 1161, 'clean': 1162, 'horrible': 1163, 'surprise': 1164, 'broke': 1165, 'lovelife': 1166, 'diet': 1167, 'eur': 1168, 'repost': 1169, 'stuck': 1170, 'cheers': 1171, 'train': 1172, 'pics': 1173, 'gratitude': 1174, 'totally': 1175, 'outside': 1176, 'yrs': 1177, 'melancholymusic': 1178, 'cover': 1179, 'deserve': 1180, 'graduation': 1181, 'case': 1182, 'praying': 1183, 'books': 1184, 'pictures': 1185, 'blm': 1186, 'upset': 1187, 'relationship': 1188, 'til': 1189, 'public': 1190, 'singing': 1191, 'finger': 1192, 'terrorism': 1193, 'received': 1194, 'action': 1195, 'states': 1196, 'double': 1197, 'planning': 1198, 'fo': 1199, 'paid': 1200, 'tampa': 1201, 'russia': 1202, 'company': 1203, 'loveit': 1204, 'wisdom': 1205, 'california': 1206, 'wild': 1207, 'ootd': 1208, 'following': 1209, 'law': 1210, 'anger': 1211, 'youth': 1212, 'australia': 1213, 'squad': 1214, 'finish': 1215, 'journey': 1216, 'learning': 1217, 'space': 1218, 'wouldn': 1219, 'benefits': 1220, 'ladies': 1221, 'netflix': 1222, 'sing': 1223, 'ticket': 1224, 'heading': 1225, 'happens': 1226, 'relaxing': 1227, 'brand': 1228, 'helping': 1229, 'spring': 1230, 'nearly': 1231, 'lord': 1232, 'review': 1233, 'add': 1234, 'beat': 1235, 'exactly': 1236, 'wakeup': 1237, 'fast': 1238, 'nation': 1239, 'behappy': 1240, 'card': 1241, 'temple': 1242, 'orange': 1243, 'ness': 1244, 'hotel': 1245, 'chicago': 1246, 'box': 1247, 'girlfriend': 1248, 'longer': 1249, 'nails': 1250, 'passed': 1251, 'christina': 1252, 'begins': 1253, 'igers': 1254, 'anime': 1255, 'analytics': 1256, 'question': 1257, 'hold': 1258, 'count': 1259, 'yours': 1260, 'essentialoils': 1261, 'eating': 1262, 'expect': 1263, 'events': 1264, 'knows': 1265, 'drawing': 1266, 'legend': 1267, 'weak': 1268, 'south': 1269, 'iphone': 1270, 'ignorance': 1271, 'maga': 1272, 'disgusting': 1273, 'movies': 1274, 'tho': 1275, 'bjp': 1276, 'cut': 1277, 'english': 1278, 'link': 1279, 'ireland': 1280, 'product': 1281, 'lets': 1282, 'bar': 1283, 'shootings': 1284, 'ma': 1285, 'em': 1286, 'songs': 1287, 'lyrics': 1288, 'ugh': 1289, 'creative': 1290, 'reasons': 1291, 'worry': 1292, 'euros': 1293, 'flagday': 1294, 'de': 1295, 'above': 1296, 'plan': 1297, 'works': 1298, 'entire': 1299, 'collection': 1300, 'passion': 1301, 'near': 1302, 'straight': 1303, 'religion': 1304, 'foodporn': 1305, 'muslims': 1306, 'bro': 1307, 'deal': 1308, 'kitty': 1309, 'tour': 1310, 'land': 1311, 'gamedev': 1312, 'begin': 1313, 'animal': 1314, 'shi': 1315, 'idwp': 1316, 'ya': 1317, 'losing': 1318, 'allow': 1319, 'texas': 1320, 'definitely': 1321, 'bored': 1322, 'turned': 1323, 'between': 1324, 'shoot': 1325, 'key': 1326, 'colombia': 1327, 'front': 1328, 'lie': 1329, 'apparently': 1330, 'sadly': 1331, 'played': 1332, 'goodtimes': 1333, 'europe': 1334, 'stream': 1335, 'brilliant': 1336, 'yum': 1337, 'stress': 1338, 'lebron': 1339, 'heaven': 1340, 'thats': 1341, 'taken': 1342, 'bigot': 1343, 'match': 1344, 'google': 1345, 'speech': 1346, 'winter': 1347, 'released': 1348, 'humpday': 1349, 'lack': 1350, 'greatest': 1351, 'schools': 1352, 'watched': 1353, 'ripchristinagrimmie': 1354, 'spent': 1355, 'studio': 1356, 'round': 1357, 'calgary': 1358, 'filled': 1359, 'powerful': 1360, 'faces': 1361, 'project': 1362, 'natural': 1363, 'boss': 1364, 'society': 1365, 'imagine': 1366, 'price': 1367, 'fat': 1368, 'dude': 1369, 'positivevibes': 1370, 'grimmie': 1371, 'market': 1372, 'worse': 1373, 'within': 1374, 'ball': 1375, 'delicious': 1376, 'cream': 1377, 'fab': 1378,

In [29]:
X = padded
y = df['label'].values

## Train-Test Split

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [32]:
X_train

array([[ 159,   17, 1501, ...,   31,  154,    0],
       [  92,   86,  451, ...,    0,    0,    0],
       [ 858,   49,   27, ..., 3175, 2098,    0],
       ...,
       [   4, 3589,  186, ...,    0,    0,    0],
       [4914,    1, 1071, ...,    0,    0,    0],
       [  12, 1758,   14, ...,    0,    0,    0]],
      shape=(25569, 22), dtype=int32)

## Model Building

In [33]:
from tensorflow import keras

In [37]:
model_rnn = keras.models.Sequential()
model_rnn.add(keras.layers.Embedding(input_dim=10000,output_dim=128,input_length=40))
model_rnn.add(keras.layers.SimpleRNN(64,return_sequences=False))
model_rnn.add(keras.layers.Dense(128,activation='relu'))
model_rnn.add(keras.layers.Dropout(0.4))
model_rnn.add(keras.layers.Dense(1,activation='sigmoid'))

model_rnn.build(input_shape=(None,40))
model_rnn.summary()

c:\Users\admin\miniconda3\envs\base_ml\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 40, 128)        │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 64)             │        12,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,300,801 (4.96 MB)

 Trainable params: 1,300,801 (4.96 MB)

 Non-trainable params: 0 (0.00 B)

## Training

In [38]:
model_rnn.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy']
                  )

In [39]:
history = model_rnn.fit(X_train,
                        y_train,
                        epochs=10,
                        batch_size=32
                        )

Epoch 1/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9295 - loss: 0.2434
Epoch 2/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9380 - loss: 0.2057
Epoch 3/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9597 - loss: 0.1219
Epoch 4/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9732 - loss: 0.0806
Epoch 5/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9833 - loss: 0.0539
Epoch 6/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9880 - loss: 0.0398
Epoch 7/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9898 - loss: 0.0340
Epoch 8/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9892 - loss: 0.0322
Epoch 9/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9926 - loss: 0.0242
Epoch 10/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9944 - loss: 0.0182

## Evaluation

In [40]:
pred = model_rnn.predict(X_test)

200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [44]:
pred_labels = (pred > 0.5).astype(int)
pred_labels.flatten()

array([0, 0, 0, ..., 0, 0, 0], shape=(6393,))

In [45]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, pred_labels))
print(classification_report(y_test, pred_labels))

Accuracy: 0.9479117785077429
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      5942
           1       0.66      0.54      0.60       451

    accuracy                           0.95      6393
   macro avg       0.81      0.76      0.78      6393
weighted avg       0.94      0.95      0.95      6393